### ISSUE TITLE
5.4.4. Working with Application Menu: Missing explanation params and permissions

### ISSUE THREAD

**Issue by PetrichorXyz** [cuba-platform/studio-docs#24]
![image](https://user-images.githubusercontent.com/2332343/77572407-34b84a80-6ecf-11ea-85eb-7cdb78e1dc32.png)

Missing explanation about how to work with params and permissions. For example this screen:
![image](https://user-images.githubusercontent.com/2332343/77572722-c45df900-6ecf-11ea-81ec-de5e2db7c041.png)

**Comment by alexbudarov** [comment]
Added brief description here.
https://github.com/cuba-platform/studio-docs/commit/14323b3d926ba8f6796cc2a5ee79b71fe1ae57d6

More detailed information is available in the developer's manual: https://doc.cuba-platform.com/manual-7.2/menu.xml.html
