### ISSUE TITLE
Describe Install handlers generation for Table and DataGrid columns

### ISSUE THREAD

**Issue by alexander-shustanov** [cuba-platform/studio-docs#3]
https://youtrack.haulmont.com/issue/STUDIO-5371

To generate column install handler navigate to the column in screen descriptor and use `Create component Install handler` intention.

**Comment by alexbudarov** [comment]
We can't just describe only this intention.
We would need to enumerate and describe all existing intentions which may be not obvious to users.

**Comment by alexbudarov** [comment]
I think that Screen Designer's Handlers and adding delegates to Inject dialog is enough.
