### ISSUE TITLE
Document how to install new Project SDK

### ISSUE THREAD

**Issue by sukhova** [cuba-platform/studio-docs#8]
### Environment

- Documentation version: 7.0

### Description of the bug or enhancement

Please add instructions for the new user. 
Let's say he just installed IDEA and CUBA plugin.
When he creates a new project, no SDKs are installed for the IntelliJ IDEA.

**Comment by alexbudarov** [comment]
We can just give link to existing IntelliJ IDEA documentation page

**Comment by alexbudarov** [comment]
I've checked on Windows and Linux, with IDEA 2019.2. IDEA automatically discovers JDK that are installed into common places (program files, /usr/lib/jvm).
So I think additional explanation is not necessary.
